services:
    db:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: supersecurepass123
            POSTGRES_USER: db_user
            POSTGRES_DB: blog_db
    redis:
        image: redis
        ports:
          - 6379:6379